var Styleguide = require('../lib/index.js');

var styleguide = new Styleguide({
  srcFolder: 'example/assets/css/',
  distFolder: 'example/styleguide/',
  distComponentFolder: 'components/',
  distFilesExtensions: 'html',

  beforeCompilation: function(MardowknStr){
    /* Add MIT License */
    return MardowknStr + '\n' + '## License: MIT';
  },
  afterCompilation: function(HtmlStr){
    /* Add a footer */
    return HtmlStr + '<footer>Generated by <a target="_blank" href="https://github.com/onaliugo/node-styleguide">Node-styleguide</a> </footer>';
  }
});

styleguide.generate();
